INFO:__main__:start
INFO:C:\Users\USER\Documents\github_personal\study\04_python\12_logging\main.py:start
INFO:C:\Users\USER\Documents\github_personal\study\04_python\12_logging\main.py:start
INFO:12_logging.main.py:start
INFO:C:\Users\USER\Documents\github_personal\study\04_python\12_logging\main.py:start
INFO:C:\Users\USER\Documents\github_personal\study\04_python\12_logging\main.py:start
INFO:12_logging.main.py:start
INFO:12_logging.main.py:info ¸Þ½ÃÁöÀÔ´Ï´Ù.
WARNING:12_logging.main.py:warning ¸Þ½ÃÁöÀÔ´Ï´Ù.
ERROR:12_logging.main.py:error ¸Þ½ÃÁöÀÔ´Ï´Ù.
INFO:12_logging.main.py:info ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
WARNING:12_logging.main.py:warning ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
ERROR:12_logging.main.py:error ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
INFO:12_logging.main.py:info ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
WARNING:12_logging.main.py:warning ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
ERROR:12_logging.main.py:error ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
INFO:12_logging.main.py:info ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
WARNING:12_logging.main.py:warning ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
ERROR:12_logging.main.py:error ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
INFO:12_logging.main.py:info ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
WARNING:12_logging.main.py:warning ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
ERROR:12_logging.main.py:error ë©”ì‹œì§€ìž…ë‹ˆë‹¤.
